USE [master]
GO

/****** Object:  Database [sqlserver]    Script Date: 10/8/2024 6:36:53 PM ******/
DROP DATABASE [sqlserver]
GO

/****** Object:  Database [sqlserver]    Script Date: 10/8/2024 6:36:53 PM ******/
CREATE DATABASE [sqlserver]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'sqlserver', FILENAME = N'/var/opt/mssql/data/sqlserver.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'sqlserver_log', FILENAME = N'/var/opt/mssql/data/sqlserver_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [sqlserver].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [sqlserver] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [sqlserver] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [sqlserver] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [sqlserver] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [sqlserver] SET ARITHABORT OFF 
GO

ALTER DATABASE [sqlserver] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [sqlserver] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [sqlserver] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [sqlserver] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [sqlserver] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [sqlserver] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [sqlserver] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [sqlserver] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [sqlserver] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [sqlserver] SET  DISABLE_BROKER 
GO

ALTER DATABASE [sqlserver] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [sqlserver] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [sqlserver] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [sqlserver] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [sqlserver] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [sqlserver] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [sqlserver] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [sqlserver] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [sqlserver] SET  MULTI_USER 
GO

ALTER DATABASE [sqlserver] SET PAGE_VERIFY NONE  
GO

ALTER DATABASE [sqlserver] SET DB_CHAINING OFF 
GO

ALTER DATABASE [sqlserver] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [sqlserver] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [sqlserver] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [sqlserver] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [sqlserver] SET DATA_RETENTION OFF 
GO

ALTER DATABASE [sqlserver] SET QUERY_STORE = ON
GO

ALTER DATABASE [sqlserver] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [sqlserver] SET  READ_WRITE 
GO

